name: main
on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          py: 3.9
          toxenv: flake8
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
      if: matrix.py != '3.12-dev'
    - uses: deadsnakes/action@v3.0.1
      with:
        python-version: ${{ matrix.py }}
      if: matrix.py == '3.12-dev'
    - run: pip install tox
    - run: tox -e ${{ matrix.toxenv }}
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
